title: Angular
caseStyle: camelCase
supportLevel: production
sdk: "sentry.javascript.browser"
categories:
  - browser
redirect_from:
  - /clients/javascript/integrations/angular2/
  - /clients/javascript/integrations/angularjs/
  - /platforms/javascript/angular/
